client_config_backend: 'settings'
client_config:
  client_id: "{client_id from client_secrets.json"
  client_secret: "{cleint_secret from client_secrets.json}"

save_credentials: True
save_credentials_backend: 'file'
save_credentials_file: 'creds.json'

oauth_scope:
  - "https://www.googleapis.com/auth/drive"
