client_config_backend: settings
client_config:
  client_id: 18520452693-b2umi3tgov9haa2el21ess3t8cd9eq26.apps.googleusercontent.com
  client_secret:  KbnFZtv2qH-xtMVOBv9rTV0L

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.readonly
