client_config_backend: settings
client_config:
  client_id: 18520452693-rd2gc90jniddaj35elpp3mnrj9m40apn.apps.googleusercontent.com
  client_secret:  NXwJC55mbm9-jkja5KlCu_sr

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.readonly
